function log_form = generated_function(a,v,x)
%GENERATED_FUNCTION
%    LOG_FORM = GENERATED_FUNCTION(A,V,X)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    16-Dec-2024 21:57:31

t2 = x.^2;
t3 = t2+1.0;
t4 = sqrt(t3);
log_form = (a.*(log(t4+x)+t4.*x))./(v.*2.0);
