# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        cd "2022C古代玻璃制品成分分析/python和matlab代码"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 drawp10.py
        python3 xishu.py
        python3 analysis.py

    - name: Run Python scripts for 2022A
      run: |
        cd "2022A波浪能最大输出功率OK/python代码"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python3 text/text1.py
        python3 T1/T1.1.py
        python3 T1/T1.2.py

    - name: Install Jupyter
      run: |
        python3 -m pip install jupyter nbconvert

    - name: Run Jupyter notebooks for 2021C
      run: |
        cd "2021C原材料的订购与运输/python代码"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        jupyter nbconvert --to script --execute p1.ipynb --output p1.py
        python3 p1.py

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
